Feature/junghoon views
wecode-bootcamp-korea/35-backend-westagram-4 pull request #14
Opened 2022-07-08 07:28 UTC by fkelfk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-08 08:21 UTC, Kang-kyunghun requested changes

2022-07-08 08:21 UTC, Kang-kyunghun commented on students/junghoon/westagram/urls.py
> +]
```suggestion
    path('/users', include('user.urls')),
]
```

2022-07-08 08:21 UTC, Kang-kyunghun commented on students/junghoon/user/urls.py
> +]
```suggestion
urlpatterns = [
    path('/signup', SignupView.as_view()),
]
```

2022-07-08 08:21 UTC, Kang-kyunghun commented on students/junghoon/user/views.py
> +                return JsonResponse({"message": "PASSWORD_IS_NOT_VALID"}, status=401)
1. 정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.
2. 정규 표현식 같은 경우 변수라기 보다는 상수입니다. python에서 상수는 대문자로 만듭니다.

```suggestion
        REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
        REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

        if not re.match(REGEX_EMAIL, data['email'):
            return JsonResponse({'message':'EMAIL_IS_NOT_VALID'}, status=400)
         
        if not re.match(REGEX_PASSWORD, data['password'):
            return JsonResponse({'message':'PASSWORD_IS_NOT_VALID'}, status=400)
```

2022-07-08 08:27 UTC, fkelfk commented on students/junghoon/westagram/urls.py
> +]
감사합니다!

2022-07-08 08:27 UTC, fkelfk commented on students/junghoon/user/urls.py
> +]
APPEND_SLASH = False를 알게 되었습니다.

2022-07-08 08:59 UTC, fkelfk commented on students/junghoon/user/views.py
> +                return JsonResponse({"message": "PASSWORD_IS_NOT_VALID"}, status=401)
re.match 할때 컴파일을 수행해서 해줄 필요가 없다고 이해 했습니다.
감사합니다.

2022-07-11 01:26 UTC, Kang-kyunghun requested changes

2022-07-11 01:26 UTC, Kang-kyunghun commented on students/junghoon/westagram/urls.py
> +    path('/user', include('user.urls')),
1. 제거 이 부분에 잘 못된 가이드를 드렸습니다. 제가 알려드린데로 코드를 수정을 하고 테스트 진행 해보셨나요? 아마 진행이 안 되었을 것 같은데 확인해 주세요.
2. user 보다는 users로 해주시면 좋을 것 같습니다. 정확한 이유는 나중에 RESTful API에 대해 배우실텐데 그 전에 이유가 궁금하시면 라운지 시간에 질문해 주세요.

```suggestion
    path('users', include('user.urls')),
```

2022-07-11 01:26 UTC, Kang-kyunghun commented on students/junghoon/user/views.py
> +            REGEX_PASSWORD        = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
```suggestion
            data            = json.loads(request.body)
            name            = data['name']
            password        = data['password']
            email           = data['email']
            contact         = data['contact']
            REGEX_EMAIL     = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
            REGEX_PASSWORD  = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
```

2022-07-11 01:26 UTC, Kang-kyunghun commented on students/junghoon/user/views.py
> +            )
```suggestion
            User.objects.create(
                name     = name,
                email    = email,
                password = password,
                contact  = contact,
            )
```

2022-07-11 02:31 UTC, fkelfk commented on students/junghoon/westagram/urls.py
> +    path('/user', include('user.urls')),
1. http://127.0.0.1:8000//user/signup으로 접속해야 했습니다.
2. 넵! 배우고 이해가 안가면 질문하겠습니다.

2022-07-11 02:32 UTC, fkelfk commented on students/junghoon/user/views.py
> +            REGEX_PASSWORD        = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
감사합니다!

2022-07-11 02:32 UTC, fkelfk commented on students/junghoon/user/views.py
> +            )
확인했습니다!

2022-07-11 02:51 UTC, merged