[전은형] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/35-backend-westagram-4 pull request #20
Opened 2022-07-11 08:20 UTC by ooooo5h

## 수정 사항 간략한 한줄 요약
- 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
- 회원가입 클래스에 비밀번호 암호화 로직 추가
- 암호화 로직 추가 전, 사용자로부터 입력받은 데이터 검증 부터 실시 
- salting과 key stretching을 이용한 단방향 암호화 bcrypt 라이브러리 사용
- string을 해싱할 때는 인코딩해서 bytes형으로 변환함
- DB 저장은 bytes를 디코딩하여 string형으로 변환함

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-11 08:53 UTC, fkelfk commented on students/eunhyung/users/views.py
> +                password     = hashed_password.decode('utf-8'),
LGTM

2022-07-11 11:38 UTC, WorkYong commented on students/eunhyung/users/views.py
> +                password     = hashed_password.decode('utf-8'),
GOOD!

2022-07-11 17:10 UTC, Kang-kyunghun requested changes

2022-07-11 17:10 UTC, Kang-kyunghun commented on students/eunhyung/users/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
password를 검증 전에 hash를 진행 하셨는데, hash부터 하는 것이 아니고 검증이 된 후에 hash를 진행하는 것이 더 좋을 것 같습니다.

2022-07-11 22:12 UTC, ooooo5h commented on students/eunhyung/users/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
클라이언트로부터 입력받은 데이터를 선 검증 후 hash진행하기!! 넵!!🫡

2022-07-11 22:56 UTC, ooooo5h commented on students/eunhyung/users/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
멘토님!! 코드를 수정하면서 궁금한 점이 생겨서요!

password hash를 먼저 진행한 코드에서 실행을 하여도
클라이언트로부터 입력받은 password가 없다면 'KEY_ERROR'로, 
입력받은 password가 정규식과 일치하지 않는 경우에도 'Password is invalid.'로 상황에 맞는 에러메세지가 잘 출력됩니다.

하지만 클라이언트로부터 받은 데이터를 먼저 검증 후 hash를 진행해야하는 이유는.. 무엇인가요..?? 저번 세션때 말씀하셨듯 사용자의 데이터는 선 검증 후 처리가 필요하니까 검증을 먼저해야한다는 이론은 알고 있는데, 제 코드도 (제 생각에는) 실행이 잘되니까 궁금증이 생겼습니당....

2022-07-12 02:07 UTC, Kang-kyunghun commented on students/eunhyung/users/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
코드는 정상적으로 작동 합니다. 

hash를 하는 이유는 데이터에비스에 암호화 된  비밀번호를 저장하기 위함 입니다. 
그렇다면 데이터베이스에 저장해도 되는 비밀번호를 암호화 해야 됩니다.

암호화를 진행 한 후에 암호화 전의 값을 확인해도 되지만, 어떠한 작업을 수행하기 전에 해당 작업을 수행해도 되는지 먼저 판단하는 것이 사람들이 판단하기에 조금 더 논리적이라고 생각 됩니다.

나중에 다른 사람이 코드를 볼 때도 조금 더 코드를 읽어가는데 편하고, 비밀번호가 조건에 맞지 않는다면 불필요한 암호화 작업을 하지 않아도 됩니다.

2022-07-12 02:08 UTC, merged

2022-07-12 02:16 UTC, ooooo5h commented on students/eunhyung/users/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
진짜 감사합니다!!! 🙏