[황유정] Mission 6: 로그인 JWT 발급
wecode-bootcamp-korea/35-backend-westagram-4 pull request #25
Opened 2022-07-12 07:33 UTC by xoxowo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원 로그인 시 암호화 로직 변경, 로그인 성공 시 jwt 발급 
		 
## 수정 사항들 자세한 내용
- 회원 로그인 시 비밀번호 확인 로직 추가 및 테스트
- 로그인 성공 시 jwt 발급 확인

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-12 08:51 UTC, WorkYong commented on students/yujeong/users/views.py
> +from my_settings  import SECRET_KEY, ALGORITHM
깔끔합니다

2022-07-12 08:52 UTC, fkelfk commented on students/yujeong/users/views.py
> +            if User.objects.filter(email=data['email']).exists() :
띄어쓰기가 되어있어요

2022-07-13 01:42 UTC, kyeongraekim requested changes

2022-07-13 01:42 UTC, kyeongraekim commented on students/yujeong/users/views.py
> +            if User.objects.filter(email=data['email']).exists() :
해당부분 동기분께서 잘 말씀해주신 것 처럼 colon 시작전 whitespace 제거해주세요~

2022-07-13 01:42 UTC, kyeongraekim commented on students/yujeong/users/views.py
> +            if User.objects.filter(email=data['email']).exists() :
위 email이라는 변수에 잘 담아준 값을 57번라인 필터 메소드에서 재사용하는게 어떨까요?

2022-07-13 01:42 UTC, kyeongraekim commented on students/yujeong/users/views.py
> +                else :
이곳에서의 추가 Else 로의 논리적 분기는 필요 없을 것 같네요! 그 해당되는 사유를 곰곰히 생각해보시고 코멘트로 남겨주세요~

2022-07-13 04:27 UTC, xoxowo commented on students/yujeong/users/views.py
> +            if User.objects.filter(email=data['email']).exists() :
exists() : 요부분 말씀하시는걸까요??

2022-07-13 04:37 UTC, xoxowo commented on students/yujeong/users/views.py
> +            if User.objects.filter(email=data['email']).exists() :
확인하여 수정했습니다!

2022-07-13 04:42 UTC, xoxowo commented on students/yujeong/users/views.py
> +                else :
다시 확인해보니 해당 분기에서 비밀번호가 일치하지않을 경우 바로 리턴 하게끔 작성하면 됐었네요... 말씀해주신 부분 이해했습니다!

2022-07-13 05:51 UTC, kyeongraekim requested changes

2022-07-13 05:51 UTC, kyeongraekim commented on students/yujeong/users/views.py
> +            return JsonResponse({"message": "INVALID_USER"}, status = 401)
전체 논리 흐름을 혹시 180도 반대 방향으로 바꾸어서 가장 앞단에서 if not으로 시작한 논리로 미리 invalid_user를 걸러내고, 맨 마지막에 모든 여과장치를 잘 훑고 넘어갔을 때 올바른 token을 반환하는 방법으로 리팩토링 해보는 것은 어떨까요? 두 개의 기능선에서는 큰차이는 없지만 같은결과를 두개의 다른 논리로 전개해보는 연습을 한 번 시도해보세요~

2022-07-13 08:25 UTC, xoxowo commented on students/yujeong/users/views.py
> +            return JsonResponse({"message": "INVALID_USER"}, status = 401)
네 알겠습니다 !

2022-07-14 05:27 UTC, Kang-kyunghun requested changes

2022-07-14 05:27 UTC, Kang-kyunghun commented on students/yujeong/users/views.py
> +               return JsonResponse({"message": "INVALID_USER_Password error"}, status = 401)
로그인 에러 같은 경우 아이디와 비밀번호 중에 어떤 것이 잘 못 되었는지 모르게 하는 것이 좋습니다.
```suggestion
               return JsonResponse({"message": "INVALID_USER"}, status = 401)    
```

2022-07-14 05:27 UTC, Kang-kyunghun commented on students/yujeong/users/views.py
> +            return JsonResponse({"message": "INVALID_USER _not macth"}, status = 400)
```suggestion
        except User.DoesNotExist:               
            return JsonResponse({"message": "INVALID_USER"}, status = 400)
```

2022-07-14 06:05 UTC, xoxowo commented on students/yujeong/users/views.py
> +            return JsonResponse({"message": "INVALID_USER _not macth"}, status = 400)
확인 했습니다.

2022-07-14 07:06 UTC, merged