[황유정] Mission 2: 모델링
wecode-bootcamp-korea/35-backend-westagram-4 pull request #6
Opened 2022-07-07 07:45 UTC by xoxowo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- yujeong/user/models.py 내용 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- user app 생성 후 models.py에  User 테이블 생성 

## 기타 질문 및 특이 사항
- 없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-07 08:09 UTC, Kang-kyunghun requested changes
모델 수정 후 makemigrations을 진행하여 에러가 없는지 확인해 주세요.

2022-07-07 08:09 UTC, Kang-kyunghun commented on students/yujeong/users/models.py
> +    user_phone_number = models.CharField(max_length = 50)
1. 속성명 앞에 user_는 모두 제거 해주세요. User table에 있는 속성이기 때문에 없어도 충분히 의미 전달이 됩니다.
2. pw 처럼 변수명을 줄여서 사용하는 것은 지양해 주세요.
3. email 필드에는 unique 속성을 추가하여 중복 저장을 방지해 주세요.
4. id 가 우리가 일반적으로 생각하는 그 ID 라면 username을 ID의 역할로 많이 사용 됩니다.
5. password의 max_length는 추후 암호화한 값이 들어갈 예정이기 때문에 200으로 늘려 주세요.
```suggestion
    name         = models.CharField(max_length = 20)
    email        = models.EmailField(max_length = 45)
    username     = models.CharField(max_length = 50)
    password     = models.CharField(max_length = 20)
    phone_number = models.CharField(max_length = 50)
```

2022-07-08 00:38 UTC, autoboy4commit commented on students/yujeong/users/views.py
> +from django.views import View
`users/views.py`에 모듈들을 import 하는 위의 코드들은 현재 modeling 브랜치의 작업 내용과 맞지 않습니다.
Mission 3 부터는 해당 리뷰가 반영되도록 신경써주세요!!  :) 
(`feature/yujeong-model` 브랜치의 작업은 모델링과 관련한 작업만 이뤄져야 합니다~!)

2022-07-08 00:38 UTC, autoboy4commit commented
유정님~~ commit 후 Push 뒤에는 항상 라벨 상태 확인하여 알맞게 수정해주세요!

2022-07-08 00:39 UTC, autoboy4commit commented
LGTM 🚀

2022-07-08 00:39 UTC, merged