Feature/junghoon models
wecode-bootcamp-korea/35-backend-westagram-4 pull request #7
Opened 2022-07-07 08:46 UTC by fkelfk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- models.py 작성 및 migrations
- 테이블 속성 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-07 10:28 UTC, Kang-kyunghun requested changes

2022-07-07 10:28 UTC, Kang-kyunghun commented on students/junghoon/junghoon/models.py
> +    email      = models.CharField(max_length=200, help_text='최대 200글자 내로 입력하세요.', unique=True)
email의 help_text 속성을 주신 이유를 코멘트로 남겨주세요.

2022-07-07 10:28 UTC, Kang-kyunghun commented on students/junghoon/junghoon/models.py
> +    password   = models.TextField(null=True)
password를 TextField로 지정한 이유와 null=True 속성을 준 이유를 코멘트로 남겨주세요.

2022-07-07 10:28 UTC, Kang-kyunghun commented on students/junghoon/junghoon/models.py
> +    contact    = models.CharField(max_length=200, blank=True, null=True)
blank=True와 null=True의 차이점을 코멘트로 남겨주시고, 두 옵션을 모두 사용한 이유를 코멘트로 남겨주세요.

2022-07-07 10:28 UTC, Kang-kyunghun commented on students/junghoon/westagram/settings.py
> +    'junghoon',
app의 이름을 정훈님 이름으로 지으셨는데, users 또는 accounts처럼 실제 어떤 데이터를 주로 다루는지 판단 하시고
app 이름을 수정해 주세요.

2022-07-07 11:22 UTC, fkelfk commented on students/junghoon/westagram/settings.py
> +    'junghoon',
네

2022-07-07 11:22 UTC, fkelfk commented on students/junghoon/junghoon/models.py
> +    email      = models.CharField(max_length=200, help_text='최대 200글자 내로 입력하세요.', unique=True)
Json으로 반환하면 쓰일 일이 없을 것 같아요. 
속성 제거 하겠습니다.

2022-07-07 11:23 UTC, fkelfk commented on students/junghoon/junghoon/models.py
> +    password   = models.TextField(null=True)
다른분들의 피드백을 봐서 패스워드는 길게 설정해주는게 좋다하셨는데 
TextField가 길이에 제한이 없다고 해서 사용했어요. 
최적화 관련해서 안좋다하고 보통 쓰이는 해시함수들이 최대 길이가 8에서 128까지 인것 같아 
Charfield(max_length=200)정도로 바꾸겠습니다.
null은 뭔가 마음에 안정이 되어서 넣었어요...

2022-07-07 11:23 UTC, fkelfk commented on students/junghoon/junghoon/models.py
> +    contact    = models.CharField(max_length=200, blank=True, null=True)
blank는 입력에 관한 것이고
null은 데이터베이스에 관한 것이라 알고있습니다.
contact는 선택적으로 입력하면 어떨까 했어요.

2022-07-08 01:03 UTC, autoboy4commit commented on students/junghoon/user/models.py
> +    contact    = models.CharField(max_length=50, blank=True, null=True)
> blank는 입력에 관한 것이고
> null은 데이터베이스에 관한 것이라 알고있습니다.
> contact는 선택적으로 입력하면 어떨까 했어요.

안녕하세요 정훈님! 그런이유라면 `blank=True` 옵션만 주면 됩니다.
이유는 django convention과 관련있는데요!
관련하여 설명이 나와있는 [장고 공식문서 링크](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.Field.null)를 첨부해 드릴테니 읽어보시면 도움 될 것 같습니다 👍

2022-07-08 01:33 UTC, fkelfk commented on students/junghoon/user/models.py
> +    contact    = models.CharField(max_length=50, blank=True, null=True)
감사합니다!

2022-07-08 05:51 UTC, merged